#!/bin/sh
set -e

# Automatically added by dh_python3
if command -v py3compile >/dev/null 2>&1; then
	py3compile -p vyatta-vrrp-vci:amd64 -V 3.6-
fi
if command -v pypy3compile >/dev/null 2>&1; then
	pypy3compile -p vyatta-vrrp-vci:amd64 -V 3.6- || true
fi

# End automatically added section
# Automatically added by dh_vci_enable/UNDECLARED
deb-vci-helper install vyatta-vrrp-vci >/dev/null
# End automatically added section
